### ISSUE TITLE
Remove `DateTime` input type

### ISSUE THREAD

**Issue by thomashoneyman** [slamdata/purescript-browserfeatures#17]
The `datetime` input type is obsolete and apparently unsupported in browsers:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime
...in favor of `datetime-local`.

Halogen 3.0 noted this and removed it from the Properties module, but that change didn't make it into this library. See:
[2.0.1](https://pursuit.purescript.org/packages/purescript-halogen/2.0.1/docs/Halogen.HTML.Properties#t:InputType)
[3.0.1](https://pursuit.purescript.org/packages/purescript-halogen/3.0.1/docs/Halogen.HTML.Properties#t:InputType)

Some packages break when updating to Halogen 3.0.1 because of this (for example, the [purescript-markdown-halogen](https://github.com/slamdata/purescript-markdown-halogen/blob/master/src/Text/Markdown/SlamDown/Halogen/InputType.purs) package.

**Comment by safareli** [comment]
Thanks!
